---
title: "Course Paperwork"
format: html
toc: true
sidebar: true
editor: source
---

## Deliverable Description

Our workshop is happening in partnership with the Central Illinois Land Bank Authority, with your work products ultimately becoming part of public documents and materials that will be viewed by the public and used in decision making for CILBA and member communities. In situations where University of Illinois students are working with community partners such as this one, the university requires that all students fill out paperwork that defines how the work products from this workshop can be used.

Since this workshop focuses on implementing planning knowledge through practice, and you are in a professional graduate degree program, this workshop also calls upon you to work in a manner that is consistent with the [AICP Code of Ethics](AICP Code of Ethics 2021.pdf). I ask that you review the standards in this code (modified slightly to focus on relevant components) and affirm that your work and engagement in this class will follow the code's guidance. As mentioned in the course syllabus, any violations of our professional code of ethics will be treated as tantamount to a violation of our University's student code, and may carry similar penalties.

Please review, sign, and upload the following to Box:

1. [Course Project Agreement](UIUC-Course-Project-Master-Agreement-CILBA.pdf) (signature and related information needed on Page 10 and Page 12)

2. [Code of Ethics](UP 510 Code of Ethics and Professional Conduct.pdf) (signature and related information on Page 6)

## Submission Instructions

Upload your course paperwork as separate PDF documents to the Box using the below upload portal. Before you upload, save your files using the following naming conventions:

1. LastName_FirstName_Agreement.pdf

2. AICP Code of Ethics and Professional Conduct: LastName_FirstName_AICP.pdf

Where LastName is your surname (last name) and FirstName is your first name. Improperly named files will be considered not submitted.