---
title: "Agenda - January 30, 2026"
format: html
toc: true
editor: source
---
## Meeting Agenda

### Work Plan Development / Scheduling

- In our first session, we were introduced to CILBA, member communities, and some of the needs in which CILBA would like us to help with as part of our workshop.

- What information do we want to communicate to CILBA? In what form?

- Based upon this information, how do we want to structure our work around the deliverables we are committed to this semester?

- What examples or ideas do you have from other plans, reports, or other information?

### Member Community Information Inventory

- What information about housing and economic characteristics will help us compare across member communities? 

- What information will help us tell the broader story of housing and economic activity in central Illinois?

- What existing information can you find on member communities? Are there plans, policy documents, datasets, etc. that would be useful to our work?

### Break / Team Headshots

### Prep for 2/5 CILBA Board Meeting

- How will we introduce ourselves to representatives from member communities?

- How will we introduce our work to representatives from member communities?

- What's the best way to frame our work to community stakeholders?

### Prep for 2/6 Site Visit

- What questions do we want to make sure we have answers to during this initial visit?
