---
title: "Schedule"
format: html
toc: true
sidebar: false
editor: source
---

Our weekly workshop sessions are two hours and fifty minutes in length. For most sessions, we will start with a team meeting, open up time to work together on deliverables, and will then confer at the end of the session on our agenda for the next week. Over the course of the term, there will be some meetings and site visits that occur outside of our scheduled class time.

+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**          | **Session**                            | **Description**                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1/23/2026         | Workshop Introduction and Background   | Team meeting with Mike Davis, CILBA Executive Director                                                                                                                                             |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | Preparation:                                                                                                                                                                                       |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | Review                                                                                                                                                                                             |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   [Course Deliverables](../deliverables/deliverables.qmd)                                                                                                                                        |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   [Scope of Work](../deliverables/CILBA%202026%20Plan%20Making%20Workshop%20-%20University%20of%20Illinois%20-%20Dept%20of%20Urban%20and%20Regional%20Planning.pdf)                              |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Center for Community Progress - [What is a Land Bank?](https://communityprogress.org/blog/what-is-a-land-bank/)                                                                                |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Read [Illinois Housing Blueprint](https://ilhousingblueprint.org/wp-content/uploads/2022/11/Housing-Blueprint-2022_Final.pdf) - FY 2022 (Priority Areas, Regional Housing Markets in Illinois) |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1/30/2026         | [Information Gathering](02_agenda.qmd) | Agenda                                                                                                                                                                                             |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Check-In / Individual Updates                                                                                                                                                                  |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Work Plan Development / Scheduling                                                                                                                                                             |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Member Community Information Inventory                                                                                                                                                         |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Break / Team Headshots                                                                                                                                                                         |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Prep for 2/5 CILBA Board Meeting                                                                                                                                                               |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Prep for 2/6 Site Visit                                                                                                                                                                        |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2/5/2025          | CILBA Board Meeting (4:30 - 6:30 pm)   | Champaign Public Library ([map](https://maps.app.goo.gl/bMhbUsJLChjgficu5))                                                                                                                        |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | Conference Room 215                                                                                                                                                                                |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2/6/2026          | Site Visit                             | Casey / Mattoon site visit (8:50 am - 5pm)                                                                                                                                                         |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | Meet at TBH west parking lot at 8:50 AM.                                                                                                                                                           |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2/13/2026         |                                        |                                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2/20/2026         |                                        |                                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2/27/2026         | Independent Work Day                   | No Workshop Meeting                                                                                                                                                                                |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3/6/2026          |                                        | Project Check in / Engagement Planning                                                                                                                                                             |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Mike Davis will join us 9am - 11am                                                                                                                                                             |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3/13/2026         |                                        | Check-in (9-10am)                                                                                                                                                                                  |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Update on outreach                                                                                                                                                                             |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Update on site visits                                                                                                                                                                          |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Work time / consulting with Andrew                                                                                                                                                             |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3/20/2026         | Spring Break - No Class                |                                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3/27/2026         |                                        | Check-in (by appointment)                                                                                                                                                                          |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | Mattoon Site Visit / Data Collection                                                                                                                                                               |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4/3/2026          |                                        | Check-in                                                                                                                                                                                           |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Update on site visits                                                                                                                                                                          |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Review report chapters and narrative                                                                                                                                                           |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | -   Discuss presentation to CILBA board                                                                                                                                                            |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4/9/2026          | CILBA Board Meeting                    | CILBA Board Meeting                                                                                                                                                                                |
|                   |                                        |                                                                                                                                                                                                    |
|                   |                                        | 4:30 - 6:00 pm                                                                                                                                                                                     |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4/10/2026         |                                        |                                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4/17/2026         |                                        |                                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4/24/2026         |                                        |                                                                                                                                                                                                    |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5/1/2026          | Independent Work Day                   | No Workshop Meeting                                                                                                                                                                                |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Week of 5/4 (TBD) | CILBA Special Board Meeting            | Final Presentation to CILBA Board                                                                                                                                                                  |
+-------------------+----------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
